---
title: "Research"
---

I am broadly interested in the decision aspects of Bayesian computational statistics and machine learning. In particular, my research focuses on developing **sequential Bayesian designs** -- such as active learning and Bayesian optimization -- for a wide range of application areas including *probabilistic numerics* and *ocean engineering*. I am also exploring what **post-Bayesian** ideas could offer for more robust, efficient decision-making. 

Oftentimes, a **Gaussian process** is the default emulator model class for systems of interest in decision-making, so much of my research is also dedicated to devising scalable and robust Gaussian process inference.

## Publication

[Google Scholar](https://scholar.google.co.uk/citations?user=iSgEv0cAAAAJ&hl=en)
      
### Preprints

### Publications and Workshop Papers

- Zhang, R. Y., Astfalck, L. C., Cripps, E. J., and Leslie, D. S., Moss, H. B. (2026). *BALLAST: Bayesian Active Learning with Look-ahead Amendment for Sea-drifter Trajectories under Spatio-Temporal Vector Fields.* **International Conference on Machine Learning (ICML)**. [[arxiv]](https://arxiv.org/abs/2509.26005) [[code]](https://github.com/ShuSheng3927/BALLAST) [[talk]](https://youtu.be/lggo0HE9ALM?si=y0zkR8x47QUDaN2_)

- Iguchi, Y., Livingstone, S., Nüsken, N., Vasdekis, G., & Zhang, R. Y. (2026). *Skew-symmetric schemes for stochastic differential equations with non-Lipschitz drift: an unadjusted Barker algorithm.* **IMA Journal of Numeical Analysis**. [[arxiv]](https://arxiv.org/abs/2405.14373) [[paper]](https://doi.org/10.1093/imanum/draf147) [[code]](https://github.com/ShuSheng3927/skew_symmetric_SDE) 

- Zhang, R. Y., Moss, H. B., Astfalck, L. C., Cripps, E. J., and Leslie, D. S. (2024). *BALLAST: Bayesian Active Learning with Look-ahead Amendment for Sea-drifter Trajectories*. **NeurIPS 2024 Workshop on Bayesian Decision-making and Uncertainty**. [[OpenReview]](https://openreview.net/pdf?id=sKjBnOQwtO) [[slides]](files/BALLAST_workshop.pptx) [[talk]](https://youtu.be/1W5YQzI1yaQ?si=zLQn13T3Xn0lcBgv) 