---
title: "Resources"
---

## Academic Groups and Organisations

### Groups

- [Lancaster CSML](https://lu-csml.github.io)

- [Lancaster AI Reading Group](https://lai-reading-group.github.io)

- [UCL Fundamentals of Statistical Machine Learning](https://fsml-ucl.github.io)

- [GP Seminar Series](https://gp-seminar-series.github.io)


### Organisations

- [Prob_AI Hub](https://www.probai.uk)

- [STOR-i](https://www.lancaster.ac.uk/stor-i/)

- [TIDE](https://tide.edu.au)


## Links

### LaTeX Tools

- [BibTeX Tidy](https://flamingtempura.github.io/bibtex-tidy/index.html), tidy up .bib files

- [LaTeX Table Generator](https://www.tablesgenerator.com), make a table as if you are in excel then convert to LaTeX codes

- [Quiver](https://q.uiver.app), draw commuative diagrams using drags and pulls


### Statistics / ML 

- [MCMC Interactive Gallery](https://chi-feng.github.io/mcmc-demo/app.html), live demo of common MCMC algorithms on interesting targets 


### Hobbies

- [WikiArt](https://www.wikiart.org), online archive for art work 

- [Xu Bing 徐冰](https://www.xubing.com), contemporary artist. Square Word Calligraphy, Book from the Sky, Background Story, Phoenix

- [Lucien Freud](http://lucianfreud.com/index.html), painter. portraits, self portraits

- [Francis Bacon](https://www.francis-bacon.com), painter. Popes, Three Studies for Figures at the Base of a Crucifixion, self portraits

- [Edward Hopper](https://en.wikipedia.org/wiki/Edward_Hopper), painter. House by the railroad, office at night 

- [Haruki Murakami 村上 春樹](https://harukimurakami.com), novelist. Hear the Wind Sing, Dance Dance Dance, The Wind-Up Bird Chronicle, After Dark, Men Without Women, What I Talk About When I Talk About Running, Novelist as a Vocation

- [Ang Lee 李安](https://en.wikipedia.org/wiki/Ang_Lee), director. Father Trilogy

- [Woody Allen](https://en.wikipedia.org/wiki/Woody_Allen), director. Annie Hall, Match point, Midnight in Paris

- [I. M. Pei 貝聿銘](https://www.pcf-p.com), architect. Pyramid, Suzhou Museum, Bank of China Tower

- [Xiang Biao 项飙](https://www.eth.mpg.de/xiang), sociologist. Global Body Shopping, Self as Methods

- [Chen Jia-Ying 陈嘉映](https://zh.wikipedia.org/zh-hans/陈嘉映), philosopher. 哲学·科学·常识, 何为良好生活, 走出唯一真理观 
